AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 17

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
